version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-express"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/app-react"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "react-test-renderer"
        update-types:
          - "major"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vitest"
          - "@vitest/*"
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
